const defaultData = {
    "church-name": "화도벧엘교회",
    "style-primary-color": "",
    "style-secondary-color": "",
    "style-accent-color": "",
    "style-font-body": "'Noto Sans KR', sans-serif",
    "style-base-font-size": "",
    "style-hero-title-size": "",
    "style-hero-title-spacing": "",
    "style-hero-title-line-height": "",
    "style-hero-subtitle-size": "",
    "style-hero-subtitle-spacing": "",
    "style-hero-desc-size": "",
    "style-section-title-size": "",
    "hero-subtitle": "",
    "hero-title": "",
    "hero-desc": "",
    "link-1-title": "예배안내",
    "link-1-desc": "거룩한 예배의 자리",
    "link-2-title": "말씀과 설교",
    "link-2-desc": "매일의 영적 양식",
    "link-3-title": "성도의 기본생활",
    "link-3-desc": "성도의 5가지 생활 수칙",
    "link-4-title": "기도 제목과 목표",
    "link-4-desc": "우리 교회 기도의 방향",
    "pastor-quote": "\"오직 예수 그리스도의 <br>복음만이 희망입니다\"",
    "pastor-name": "",
    "vision-1-title": "",
    "vision-1-desc": "",
    "vision-2-title": "",
    "vision-2-desc": "",
    "vision-3-title": "",
    "vision-3-desc": "",
    "nextgen-title": "",
    "nextgen-desc": "",
    "ng-1-title": "",
    "ng-1-desc": "",
    "ng-2-title": "",
    "ng-2-desc": "",
    "ng-3-title": "",
    "ng-3-desc": "",
    "footer-address": "경기도 남양주시 화도읍 비룡로55번길 3-35",
    "footer-tel": "",
    "hero-bg": "./uploads/file-1765187687721-163199067.png",
    "pastor-img": "./uploads/file-1765181448282-228247910.png",
    "ng-3-img": "./uploads/file-1765181501790-327915609.jpg",
    "org-1-title": "",
    "org-1-desc": "",
    "org-1-detail-desc": "",
    "org-1-img": "./uploads/file-1765181575800-654146910.jpg",
    "org-2-title": "",
    "org-2-desc": "",
    "org-2-detail-desc": "",
    "org-2-img": "./uploads/file-1765181582933-239095144.png",
    "org-3-title": "",
    "org-3-desc": "",
    "org-3-detail-desc": "",
    "org-3-img": "./uploads/file-1765181589344-631275801.png",
    "org-4-title": "",
    "org-4-desc": "",
    "org-4-detail-desc": "",
    "org-4-img": "./uploads/file-1765181595526-488149509.jpg",
    "org-5-title": "",
    "org-5-desc": "",
    "org-5-detail-desc": "",
    "org-5-img": "./uploads/file-1765181604301-29497606.jpg",
    "org-6-title": "시온성가대",
    "org-6-desc": "하나님을 찬양하는 기쁨",
    "org-6-detail-desc": "",
    "org-6-img": "./uploads/file-1767184336608-620387894.jpg",
    "phil-1-title": "",
    "phil-1-pastor": "",
    "phil-1-desc": "",
    "phil-1-detail-desc": "",
    "phil-1-img": "./uploads/file-1765181622144-50647791.jpg",
    "phil-2-title": "",
    "phil-2-pastor": "",
    "phil-2-desc": "",
    "phil-2-detail-desc": "",
    "phil-2-img": "./uploads/file-1765181629469-171240464.png",
    "phil-3-title": "",
    "phil-3-pastor": "",
    "phil-3-desc": "",
    "phil-3-detail-desc": "",
    "phil-3-img": "./uploads/file-1765181635622-366485057.jpg",
    "worshipSunday": [
        {
            "time": "오전 9:30",
            "name": "유치부 예배",
            "place": "주일학교 기관실"
        },
        {
            "time": "오전 9시 / 오후 1시",
            "name": "유,초등부 예배",
            "place": "주일학교 기관실"
        },
        {
            "time": "오전 11시",
            "name": "주일 낮 예배",
            "place": "본당 예배실"
        },
        {
            "time": "오후 1시",
            "name": "주일 오후 예배",
            "place": "본당 예배실"
        },
        {
            "time": "오전 예배 후",
            "name": "요셉청년부 예배",
            "place": "요셉 기관실"
        },
        {
            "time": "오전 예배 후",
            "name": "에스겔학생부 예배",
            "place": "에스겔 기관실"
        }
    ],
    "worshipWeekday": [
        {
            "day": "매일",
            "time": "오전 5시",
            "name": "새벽 기도회",
            "place": "본당 예배실"
        },
        {
            "day": "화요일",
            "time": "오후 2시",
            "name": "여호와닛시 기도회",
            "place": "김남숙 권사님 가정"
        },
        {
            "day": "수요일",
            "time": "오후 7:30",
            "name": "수요 예배",
            "place": "본당 예배실"
        },
        {
            "day": "금요일",
            "time": "오후 8시",
            "name": "금요 철야 예배",
            "place": "본당 예배실"
        }
    ],
    "weeklySchedule": {
        "month": "DEC",
        "day": "07",
        "events": [
            {
                "time": "09:00",
                "name": "1부 주일예배"
            },
            {
                "time": "11:00",
                "name": "2부 주일예배"
            },
            {
                "time": "13:00",
                "name": "청년부 예배"
            }
        ]
    },
    "notices": [
        {
            "id": 1,
            "title": "2025년 신년 특별 새벽기도회 안내",
            "date": "2025.12.06",
            "category": "공지",
            "content": "2025년 새해를 기도로 시작합니다.<br>일시: 1월 1일 ~ 1월 7일<br>시간: 오전 5시<br>장소: 본당"
        },
        {
            "id": 2,
            "title": "성탄 축하 발표회 및 예배",
            "date": "2025.12.05",
            "category": "행사",
            "content": "성탄의 기쁨을 함께 나눕니다.<br>일시: 12월 25일 오전 11시"
        }
    ],
    "sermons": [
        {
            "id": 3,
            "date": "2025.8.17",
            "title": "하나님의 비밀을 맡은 자",
            "scripture": "고린도전서 4:1-2",
            "preacher": "김석주목사님",
            "videoUrl": "https://www.youtube.com/embed/nU_4xk96Z8g",
            "summary": "",
            "file": "./uploads/file-1765134742302-411533394.pdf",
            "preacherImg": "./uploads/file-1765134725145-72339629.png"
        },
        {
            "id": 4,
            "date": "2025.12.7",
            "title": "행복 안에 거하는 사람들",
            "scripture": "이사야 43 : 14-21",
            "preacher": "김석주 목사님",
            "videoUrl": "https://www.youtube.com/embed/7dXcB_zw9pU",
            "summary": "이 설교 발췌문은 이사야서 43장 14절부터 21절까지의 말씀을 바탕으로, 성도들에게 **'행복 안에 거하는 사람들'**이 되도록 권면하고 있습니다. 설교자는 행복과 불행이 외부에서 찾아오는 것이 아니라 태초부터 인간의 심령 속에 공존해 왔으며, 개인이 하나님 안에 거할 때 행복하고, 마귀에게 거할 때 불행해진다고 설명합니다. 행복의 조건으로 미래(장래)에 소망을 두는 것, 하나님의 기적을 믿는 것, 그리고 하나님의 약속 안에 거하는 것 세 가지를 강조하며, 특히 부부 관계에서는 과거를 들추지 않고 미래를 이야기하며 아내가 가정을 행복하게 만들 역할이 있음을 역설합니다. 궁극적으로 성도들이 하나님의 생각과 말씀 안에 거하여 영원한 천국에 이르는 진정한 행복을 누리기를 축복하며 마칩니다.\n\n이사야 43장에 나타난 하나님의 새 일은 신자들에게 어떤 미래와 소망을 제시하는가?\n행복과 불행이 삶에 내재한다는 전제는 신자의 선택과 거함에 어떤 중요성을 부여하는가?\n장래, 기적, 그리고 약속이라는 세 가지 행복 조건들은 신앙인의 실천적 삶을 어떻게 이끄는가?\n",
            "file": "./uploads/file-1765426932065-238933095.pdf",
            "preacherImg": "./uploads/file-1765426867726-849070902.png"
        },
        {
            "id": 5,
            "date": "2025.12.14",
            "title": "멸망하는 짐승들",
            "scripture": "시편 49 : 16 - 20",
            "preacher": "김석주 목사님",
            "videoUrl": "https://www.youtube.com/embed/3I3hGtscnnc",
            "summary": "이 설교문은 화도벧엘교회 김석주 목사님의 설교를 담고 있으며, 시편 49편 16절에서 20절 말씀을 중심으로 인간이 깨달아야 할 세 가지 핵심 진리에 대해 강조하고 있습니다. 설교자는 존귀한 위치에 있으면서도 깨닫지 못하는 사람은 멸망하는 짐승과 같다고 경고하며, 인간과 짐승의 차이는 영혼의 유무에 있음을 설명합니다. 깨달아야 할 첫 번째는 하나님과 영생의 존재이며, 둘째는 진정한 구원자는 오직 예수 그리스도 한 분뿐이라는 사실이고, 마지막 세 번째는 모든 것이 하나님의 소유임을 인정해야 한다는 것입니다. 설교는 이러한 진리를 깨닫지 못하고 자기 공덕이나 세상의 것을 자랑하는 사람은 마귀의 궤계에 빠져 심판을 면치 못하고 지옥으로 가게 될 것이라고 역설합니다.\n\n인간이 멸망하는 짐승과 같지 않기 위해 깨달아야 할 세 가지 핵심 교훈은 무엇인가?\n영혼의 본질적 차이가 인간에게 영생과 심판을 가져오는 신학적 근거는 무엇인가?\n진정한 구원과 예배에서 자기 공덕이 아닌 오직 그리스도의 은혜를 강조하는 이유는 무엇인가?",
            "file": "./uploads/file-1765861594176-725837384.pdf",
            "preacherImg": "./uploads/file-1765861548445-278487454.png",
            "thumbnail": "./uploads/file-1765862365241-200938082.png"
        },
        {
            "id": 6,
            "date": "2025.12.21",
            "title": "영원한 사랑",
            "scripture": "요한복음 3 : 16",
            "preacher": "김석주 담임목사",
            "videoUrl": "https://www.youtube.com/embed/S5iMMUm7YYE?start=142",
            "summary": "2025.12.21\n영원한 사랑( 요한복음 3:16 )\n화도벧엘교회 김석주 목사님\n\n 화도벧엘교회 김석주 목사님의 성탄절 메시지로, 요한복음 3장 16절을 통해 하나님의 영원한 사랑에 대해 역설합니다. 목사님은 인생을 덧없는 나그네 길에 비유하며, 세상 끝까지 함께할 진정한 친구는 오직 예수 그리스도뿐임을 강조합니다. 특히 하나님이 세상을 사랑하신 것은 그 속의 자기 백성을 구원하기 위함이며, 예수의 희생은 선택된 이들의 죄를 대속한 사건이라고 설명합니다. 성도들에게는 주님을 본받아 자기희생적 헌신을 실천하고, 타인의 잘못을 기꺼이 용서하는 삶을 살 것을 권면합니다. 결론적으로 성탄의 참의미는 미안함과 고마움, 사랑을 나누며 주님의 영원한 사랑을 가정과 삶 속에서 증거하는 데 있습니다.\n\n하나님의 영원한 사랑이 인간의 유한한 삶과 대조되는 근본적인 이유는 무엇인가요?\n예수 그리스도의 희생을 통해 확증된 참된 사랑의 실천적 의미는 무엇인가요?\n회개와 용서가 하나님 나라의 백성으로서 영생을 누리는 데 왜 필수적인가요?",
            "file": "./uploads/file-1766401889272-627221960.pdf",
            "preacherImg": "./uploads/file-1766401207522-390159145.png",
            "thumbnail": "./uploads/file-1766401584767-897270251.png"
        },
        {
            "id": 7,
            "date": "2025.12.28",
            "title": "얍복강의 밤과 브니엘의 아침",
            "scripture": "창세기 32 :13-32",
            "preacher": "김석주목사님",
            "videoUrl": "https://www.youtube.com/embed/OFwUa4zN9Mc",
            "summary": "얍복강의 밤과 브니엘의 아침 (창세기 32 : 13 - 32 )\n화도벧엘교회  김석주 목사님\n\n본 말씀은 화도벧엘교회 김석주 목사님의 설교를 바탕으로, 야곱이 얍복강에서 겪은 영적 체험과 브니엘의 아침이 갖는 신앙적 의미를 설명합니다. 야곱은 형 에서와의 갈등이라는 절체절명의 위기 속에서 홀로 남아 천사와 씨름하며 간절히 기도했고, 결국 이스라엘이라는 새 이름을 얻으며 승리했습니다. 목사님은 이 사건을 통해 기도가 인간관계와 경제적 결핍 등 삶의 모든 난제를 해결하는 열쇠임을 강조하며 성도들을 권면합니다. 특히 하나님이 앞서 싸우시는 기도의 능력을 신뢰할 때, 두려움의 밤을 지나 축복과 희망의 아침을 맞이할 수 있다고 역설합니다. 결론적으로 이 말씀은 새해를 맞는 신자들이 기도로써 하나님의 도우심을 구하며 인생의 '브니엘 아침'을 경험하도록 독려하는 메시지를 담고 있습니다.\n\n야곱이 맞이한 브니엘의 아침은 그의 인생과 신앙에 어떠한 변화를 가져왔는가?\n얍복강에서의 간절한 기도가 인간관계와 물질적 문제를 어떻게 해결하며 하나님의 도우심을 끌어냈는가?\n두려움을 극복하고 승리한 야곱의 이야기가 오늘날 우리에게 주는 영적 교훈은 무엇인가?",
            "file": "./uploads/file-1767068927987-821560569.pdf",
            "preacherImg": "./uploads/file-1767068747639-546359016.png",
            "thumbnail": "./uploads/file-1767069631370-473003164.png"
        },
        {
            "id": 8,
            "date": "2025.12.31 송구헌신예배",
            "title": "심겨진 축복",
            "scripture": "시편 1 : 1 - 6",
            "preacher": "김석주 목사님",
            "videoUrl": "https://www.youtube.com/embed/1XZ1NYUEFYk",
            "summary": "2025년 12월 31일 송구영신 예배를 준비하고 진행하는 과정이 담긴 영상입니다. 전반부에는 찬양팀이 특송을 하고  있습니다. 예배가 시작되자 목사님께서는 성도들에게 새해를 맞이하는 축복의 메시지와 함께 심겨진 축복이라는 주제로 설득력 있는 설교를 전합니다. 특히 성경 인물인 야곱을 통해 하나님 중심의 삶과 영적 성숙의 중요성을 강조하며 교회의 역할을 역설합니다. 마지막으로 성도들은 합심하여 기도하고 찬송하며 2026년 새해를 희망차게 맞이하는 결단의 시간을 가집니다. 이 자료는 한 해를 마무리하고 새로운 시작을 준비하는 교회의 경건한 예배 현장을 생생하게 보여줍니다.\n\n새로운 한 해를 맞이하며 목사님께서 성도들에게 제시한 '심겨진 축복'의 영적 의미는 무엇입니까?\n예배 자료와 설교를 통해 나타난 2026년 새해를 향한 공동체의 핵심적인 소망과 다짐은 무엇입니까?",
            "file": "./uploads/file-1767317786044-742848498.pdf",
            "preacherImg": "./uploads/file-1767317871469-5262079.png",
            "thumbnail": "./uploads/file-1767317883472-206239169.png"
        },
        {
            "id": 9,
            "date": "2026.01.04",
            "title": "주인 되신 예수",
            "scripture": "요한복음 2 : 1 - 11 ",
            "preacher": "김석주 목사님",
            "videoUrl": "https://www.youtube.com/embed/h16wl00yWMU",
            "summary": "이 설교는 예수님을 삶의 주인으로 모시는 믿음의 중요성과 그로 인해 나타나는 기적의 원리를 다루고 있습니다. 목사님은 가나 혼인 잔치에서 물을 포도주로 바꾸신 사건을 통해, 성도가 마주하는 난관을 해결하는 열쇠는 오직 주님의 주권을 인정하는 데 있다고 강조합니다. 강연에 따르면 하나님은 졸지도 주무시지도 않으며 언제나 우리와 함께하시기에, 우리는 자신의 수단보다 기도와 인내를 우선시해야 합니다. 특히 인간의 계획이 아닌 하나님의 때를 기다리며 그분의 말씀에 절대적으로 순종할 때 비로소 삶의 현장에서 놀라운 신비와 은혜를 체험할 수 있다고 설명합니다. 결론적으로 이 말씀은 주님께 모든 것을 맡기고 그분의 이끄심을 따르는 그리스도인의 기본 자세를 일깨워 줍니다.\n\n우리 삶의 모든 영역에서 예수님을 주인으로 모시는 것이 왜 기적의 핵심입니까?\n하나님의 때와 인간의 때가 다름을 인정하는 기다림은 어떠한 영적 유익을 줍니까?\n기도 중에 주시는 말씀에 절대적으로 순종하는 자세는 어떻게 하나님의 일하심을 이끌어냅니까?",
            "file": "./uploads/file-1767592287816-555017552.pdf",
            "preacherImg": "./uploads/file-1767593760054-87796791.png",
            "thumbnail": "./uploads/file-1767592329544-222443296.png"
        },
        {
            "id": 10,
            "date": "2026.01.11 주일예배",
            "title": "하나님 중심의 삶",
            "scripture": "시편 100 : 1 - 5",
            "preacher": "김석주목사님",
            "videoUrl": "https://www.youtube.com/embed/3ImuBEa_kA8",
            "summary": "2026.1.11\n하나님 중심의 삶 (시편 100 : 1 -5 )\n화도벧엘교회  김석주 목사님\n\n이 말씀은 하나님 중심, 말씀 중심, 교회 중심의 삶을 강조하며 신앙의 본질을 일깨우는 김석주 목사님의 설교 요약입니다. 설교자는 성도가 하나님을 붙잡으려 애쓰는 수동적 태도를 넘어, 전능하신 하나님께 완전히 붙들려 사는 삶이 가장 큰 복임을 역설합니다. 특히 예배를 소중히 여기는 태도를 하나님께 붙들린 자의 핵심 증거로 제시하며, 이는 자신의 소원을 이루기 위한 도구가 아니라 자신을 깨뜨려 하나님의 목적에 맞추는 과정이어야 한다고 설명합니다. 아브라함과 아벨의 사례를 통해 형식적인 종교 행위와 참된 예배의 차이를 구분하고, 모든 문제의 해결책이 하나님 안에 있음을 강조합니다. 결론적으로 성도들이 인간적인 수단에 의지하지 않고 하나님의 은혜와 섭리에 온전히 맡기는 신앙을 통해 승리하는 한 해를 보낼 것을 독려하고 있습니다.\n\n하나님 중심, 말씀 중심, 교회 중심의 삶이 신앙생활에서 가지는 본질적인 의미는 무엇인가요?\n하나님을 붙드는 신앙과 하나님께 붙들리는 신앙은 삶의 태도에서 어떤 차이를 만드나요?\n참된 예배자가 되기 위해 하나님 앞에서 나 자신을 깨뜨리는 과정은 왜 중요한가요?",
            "file": "./uploads/file-1768189809591-478665929.pdf",
            "preacherImg": "./uploads/file-1768189737602-496915675.png",
            "thumbnail": "./uploads/file-1768189781799-825221226.png"
        }
    ],
    "sermon-date": "2025.08.17 주일예배",
    "sermon-title": "하나님의 비밀을 맡은 자",
    "sermon-scripture": "고린도전서 4:1-2",
    "sermon-preacher": "김석주 담임목사",
    "welcome-title": "",
    "welcome-desc": "",
    "pastor-greeting-title": "",
    "pastor-greeting-text": "",
    "sermon-video-url": "https://www.youtube.com/embed/nU_4xk96Z8g?start=7",
    "sermon-summary": "하나님은 외모를 보지 않으시고 중심을 보십니다. 다윗처럼 하나님의 마음에 합한 사람이 되기 위해서는...",
    "about-pastor-greeting-title": "\"하나님의 은혜가<br>여러분의 삶에 가득하기를 축복합니다\"",
    "about-pastor-greeting-text": "할렐루야! 화도벧엘교회 홈페이지를 방문해주신 <br>여러분을 진심으로 환영합니다.<br>우리 교회는 하나님의 말씀 위에 굳게 서서, <br>세상을 향해 그리스도의 사랑을 전하는 믿음의 공동체입니다.<br>이곳에서 참된 평안과 기쁨을 누리시기를 소망합니다.<br>",
    "style-pastor-quote-font": "'Noto Serif KR', serif",
    "style-pastor-quote-size": "",
    "style-pastor-quote-color": "",
    "style-greeting-title-font": "'Noto Sans KR', sans-serif",
    "style-greeting-title-size": "",
    "style-greeting-title-color": "",
    "style-pastor-greeting-font": "'Noto Sans KR', sans-serif",
    "style-pastor-greeting-size": "2",
    "style-pastor-greeting-color": "",
    "style-pastor-greeting-line-height": "",
    "ng-1-img": "./uploads/file-1765181473232-702783357.jpg",
    "ng-2-img": "./uploads/file-1765181519490-959194037.jpg",
    "header-bg-about": "./uploads/file-1765191164886-687742556.png",
    "header-bg-worship": "./images/worship_header.png",
    "header-bg-nextgen": "./uploads/file-1765452819211-706649435.png",
    "header-bg-phil": "./images/123.png",
    "header-bg-notice": "./uploads/file-1765452932347-232942125.png",
    "header-bg-org": "./uploads/file-1765452573146-638247426.jpg",
    "header-bg-family": "./images/family_life.png",
    "header-bg-newcomer": "./images/prayer_goals.png",
    "customPages": [],
    "shortcut-1-link": "",
    "shortcut-2-link": "",
    "shortcut-3-link": "",
    "shortcut-4-link": "",
    "shortcuts": {},
    "org-1-pastor": "",
    "org-2-pastor": "",
    "org-3-pastor": "",
    "org-4-pastor": "",
    "org-5-pastor": "",
    "org-6-pastor": ""
};
